version: 2

project_name: agent-fetch

before:
  hooks:
    - go test ./...

builds:
  - id: agent-fetch
    main: ./cmd/agent-fetch
    binary: agent-fetch
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    ids:
      - agent-fetch
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

release:
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
